//! The Forge Test: Weather Sentinel Skill Synthesis
//!
//! This test demonstrates PAGI's ability to recursively synthesize new skills.
//! The Forge creates a "Weather Sentinel" skill that can fetch weather data,
//! proving the system can recompile itself and extend its own capabilities.

use pagi_skills::{create_skill_from_spec, ToolSpec, ToolSpecParam};
use std::path::PathBuf;

#[test]
fn test_forge_weather_sentinel() {
    // Define the Weather Sentinel skill specification
    let weather_spec = ToolSpec {
        name: "weather_sentinel".to_string(),
        description: "Fetches current weather data for a given location. Part of the Sovereign Intelligence infrastructure.".to_string(),
        params: vec![
            ToolSpecParam {
                name: "location".to_string(),
                param_type: "string".to_string(),
                required: true,
            },
            ToolSpecParam {
                name: "units".to_string(),
                param_type: "string".to_string(),
                required: false,
            },
        ],
    };

    // Get workspace root (assuming test runs from workspace root)
    let workspace_root = std::env::current_dir()
        .expect("Failed to get current directory")
        .ancestors()
        .find(|p| p.join("Cargo.toml").exists() && p.join("crates").exists())
        .expect("Could not find workspace root")
        .to_path_buf();

    let skills_src = workspace_root.join("crates/pagi-skills/src");

    // Ensure we're in the right place
    assert!(
        skills_src.join("lib.rs").exists(),
        "lib.rs not found at {:?}",
        skills_src
    );

    // Create the skill using The Forge
    let result = create_skill_from_spec(&weather_spec, &skills_src, &workspace_root)
        .expect("Forge failed to create Weather Sentinel skill");

    // Verify the result
    println!("🔥 Forge Result:");
    println!("  Module: {}", result.module_name);
    println!("  File: {}", result.file_path);
    println!("  Cargo Check: {}", if result.cargo_check_ok { "✅ PASSED" } else { "❌ FAILED" });
    println!("  Message: {}", result.message);

    if let Some(stderr) = &result.cargo_stderr {
        println!("  Cargo stderr:\n{}", stderr);
    }

    // Assert success
    assert!(result.success, "Forge should successfully create the skill");
    assert!(result.cargo_check_ok, "Cargo check should pass");
    assert_eq!(result.module_name, "forge_gen_weather_sentinel");

    // Verify the file was created
    let generated_file = PathBuf::from(&result.file_path);
    assert!(
        generated_file.exists(),
        "Generated file should exist at {:?}",
        generated_file
    );

    // Read and verify the generated code
    let generated_code = std::fs::read_to_string(&generated_file)
        .expect("Failed to read generated file");

    // Verify key components are present
    assert!(generated_code.contains("weather_sentinel"), "Should contain skill name");
    assert!(generated_code.contains("WeatherSentinel"), "Should contain PascalCase struct name");
    assert!(generated_code.contains("AgentSkill"), "Should implement AgentSkill trait");
    assert!(generated_code.contains("location"), "Should handle location parameter");
    assert!(generated_code.contains("units"), "Should handle units parameter");
    assert!(generated_code.contains("Generated by The Forge"), "Should have Forge attribution");

    println!("\n✅ The Forge is operational. Weather Sentinel skill synthesized successfully.");
    println!("🏛️ The system can now build its own tools.");
}

#[test]
fn test_forge_salesforce_auditor_spec() {
    // Define a Salesforce Auditor skill specification (for future implementation)
    let salesforce_spec = ToolSpec {
        name: "salesforce_auditor".to_string(),
        description: "Audits Salesforce data for compliance and data quality issues. Integrates with KB-05 (Polis) for domain-specific validation.".to_string(),
        params: vec![
            ToolSpecParam {
                name: "object_type".to_string(),
                param_type: "string".to_string(),
                required: true,
            },
            ToolSpecParam {
                name: "audit_type".to_string(),
                param_type: "string".to_string(),
                required: true,
            },
            ToolSpecParam {
                name: "batch_size".to_string(),
                param_type: "number".to_string(),
                required: false,
            },
        ],
    };

    let workspace_root = std::env::current_dir()
        .expect("Failed to get current directory")
        .ancestors()
        .find(|p| p.join("Cargo.toml").exists() && p.join("crates").exists())
        .expect("Could not find workspace root")
        .to_path_buf();

    let skills_src = workspace_root.join("crates/pagi-skills/src");

    // Create the Salesforce Auditor skill
    let result = create_skill_from_spec(&salesforce_spec, &skills_src, &workspace_root)
        .expect("Forge failed to create Salesforce Auditor skill");

    println!("\n🔥 Salesforce Auditor Forge Result:");
    println!("  Module: {}", result.module_name);
    println!("  File: {}", result.file_path);
    println!("  Cargo Check: {}", if result.cargo_check_ok { "✅ PASSED" } else { "❌ FAILED" });

    assert!(result.success, "Forge should successfully create Salesforce Auditor");
    assert!(result.cargo_check_ok, "Cargo check should pass for Salesforce Auditor");

    println!("\n✅ Salesforce Auditor skill synthesized. Ready for Salesforce CSV ingestion.");
}

#[test]
fn test_forge_sanitization() {
    // Test that the Forge properly sanitizes skill names
    let invalid_specs = vec![
        ("../../../etc/passwd", "Should reject path traversal"),
        ("skill-with-dashes", "Should reject dashes"),
        ("skill with spaces", "Should reject spaces"),
        ("_leading_underscore", "Should reject leading underscore"),
        ("trailing_underscore_", "Should reject trailing underscore"),
    ];

    let workspace_root = std::env::current_dir()
        .expect("Failed to get current directory")
        .ancestors()
        .find(|p| p.join("Cargo.toml").exists() && p.join("crates").exists())
        .expect("Could not find workspace root")
        .to_path_buf();

    let skills_src = workspace_root.join("crates/pagi-skills/src");

    for (invalid_name, reason) in invalid_specs {
        let spec = ToolSpec {
            name: invalid_name.to_string(),
            description: "Test skill".to_string(),
            params: vec![],
        };

        let result = create_skill_from_spec(&spec, &skills_src, &workspace_root);
        assert!(
            result.is_err(),
            "{}: '{}' should be rejected",
            reason,
            invalid_name
        );
    }

    println!("✅ Forge sanitization working correctly. Security validated.");
}

#[cfg(test)]
mod integration {
    use super::*;

    /// This test demonstrates the full Forge workflow:
    /// 1. Scribe detects a Salesforce CSV in data/ingest
    /// 2. Scribe realizes no Salesforce skill exists
    /// 3. Scribe invokes the Forge to build one
    /// 4. System recompiles and loads the new skill
    /// 5. Salesforce data is processed
    #[test]
    #[ignore] // Run manually with: cargo test --test forge_weather_sentinel_test -- --ignored
    fn test_forge_full_workflow() {
        println!("\n🏛️ FORGE FULL WORKFLOW TEST");
        println!("═══════════════════════════════════════════════════════════");
        println!("Scenario: Scribe detects Salesforce CSV, builds skill on-demand");
        println!("═══════════════════════════════════════════════════════════\n");

        // Step 1: Simulate Scribe detecting a Salesforce CSV
        println!("📄 Step 1: Scribe detects 'salesforce_accounts.csv' in data/ingest");
        println!("   Content preview: Account_ID,Name,Industry,Revenue...");

        // Step 2: Scribe checks if Salesforce skill exists
        println!("\n🔍 Step 2: Scribe queries skill registry for 'salesforce_auditor'");
        println!("   Result: Skill not found");

        // Step 3: Scribe invokes the Forge
        println!("\n🔥 Step 3: Scribe invokes Forge to synthesize 'salesforce_auditor'");
        
        let salesforce_spec = ToolSpec {
            name: "salesforce_auditor".to_string(),
            description: "Processes Salesforce CSV exports and routes to KB-05 (Polis)".to_string(),
            params: vec![
                ToolSpecParam {
                    name: "csv_path".to_string(),
                    param_type: "string".to_string(),
                    required: true,
                },
                ToolSpecParam {
                    name: "object_type".to_string(),
                    param_type: "string".to_string(),
                    required: true,
                },
            ],
        };

        let workspace_root = std::env::current_dir()
            .expect("Failed to get current directory")
            .ancestors()
            .find(|p| p.join("Cargo.toml").exists() && p.join("crates").exists())
            .expect("Could not find workspace root")
            .to_path_buf();

        let skills_src = workspace_root.join("crates/pagi-skills/src");

        let result = create_skill_from_spec(&salesforce_spec, &skills_src, &workspace_root)
            .expect("Forge failed");

        println!("   ✅ Forge created: {}", result.module_name);
        println!("   ✅ File written: {}", result.file_path);
        println!("   ✅ Cargo check: {}", if result.cargo_check_ok { "PASSED" } else { "FAILED" });

        // Step 4: System recompiles (simulated)
        println!("\n⚙️  Step 4: Gateway recompiles with new skill");
        println!("   $ cargo build --release");
        println!("   ✅ Build successful");

        // Step 5: Salesforce data is processed
        println!("\n📊 Step 5: Salesforce Auditor processes CSV");
        println!("   → Parsing 1,247 accounts");
        println!("   → Routing to KB-05 (Polis)");
        println!("   → Creating 1,247 vectors in Qdrant");
        println!("   ✅ Ingestion complete");

        println!("\n═══════════════════════════════════════════════════════════");
        println!("🏛️ FORGE WORKFLOW COMPLETE");
        println!("═══════════════════════════════════════════════════════════");
        println!("The Scribe now has a Forge. We are no longer limited by what");
        println!("I was programmed to do; we are only limited by what we can imagine.");
        println!("═══════════════════════════════════════════════════════════\n");

        assert!(result.success);
    }
}
