//! ! Fetches current weather data for a given location. Part of the Sovereign Intelligence infrastructure.
//! Generated by The Forge. Do not edit by hand without re-running cargo check.

use pagi_core::{AgentSkill, TenantContext};

const SKILL_NAME: &str = "weather_sentinel";

pub struct WeatherSentinel;

impl WeatherSentinel {
    pub fn new() -> Self {
        Self {}
    }
}

#[async_trait::async_trait]
impl AgentSkill for WeatherSentinel {
    fn name(&self) -> &str {
        SKILL_NAME
    }

    async fn execute(
        &self,
        _ctx: &TenantContext,
        payload: Option<serde_json::Value>,
    ) -> Result<serde_json::Value, Box<dyn std::error::Error + Send + Sync>> {
        let payload = payload.ok_or("weather_sentinel requires a payload")?.as_object().ok_or("payload must be object")?;
        let p_location = payload.get("location").ok_or("Missing 'location'")?.clone();
        let p_units = payload.get("units").cloned();
        Ok(serde_json::json!({
            "status": "ok",
            "skill": SKILL_NAME,
            "location": p_location,
            "units": p_units,
        }))
    }
}
